[project]
name = "python-entsoe"
version = "0.1.0"
authors = [
    {name = "Piotr OpaÅ‚a", email = "opalapj@gmail.com"},
]
license = {text = "MIT"}
dependencies = ["entsoe-py>=0.7.8"]
requires-python = "==3.13.*"

[tool.pdm]
distribution = false
